/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedEdgeAiRouteImport } from './routes/_authed/edge-ai'
import { Route as AuthedPerformanceRouteImport } from './routes/_authed/performance'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedValueRouteImport } from './routes/_authed/value'
import { Route as ApiTimeRouteImport } from './routes/api/time'
import { Route as AuthedEventEventIdRouteImport } from './routes/_authed/event.$eventId'
import { Route as ApiCronCycleRouteImport } from './routes/api/cron.cycle'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedEdgeAiRoute = AuthedEdgeAiRouteImport.update({
  id: '/edge-ai',
  path: '/edge-ai',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPerformanceRoute = AuthedPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedValueRoute = AuthedValueRouteImport.update({
  id: '/value',
  path: '/value',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiTimeRoute = ApiTimeRouteImport.update({
  id: '/api/time',
  path: '/api/time',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedEventEventIdRoute = AuthedEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiCronCycleRoute = ApiCronCycleRouteImport.update({
  id: '/api/cron/cycle',
  path: '/api/cron/cycle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthedAdminRoute
  '/edge-ai': typeof AuthedEdgeAiRoute
  '/performance': typeof AuthedPerformanceRoute
  '/settings': typeof AuthedSettingsRoute
  '/value': typeof AuthedValueRoute
  '/api/time': typeof ApiTimeRoute
  '/event/$eventId': typeof AuthedEventEventIdRoute
  '/api/cron/cycle': typeof ApiCronCycleRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthedAdminRoute
  '/edge-ai': typeof AuthedEdgeAiRoute
  '/performance': typeof AuthedPerformanceRoute
  '/settings': typeof AuthedSettingsRoute
  '/value': typeof AuthedValueRoute
  '/api/time': typeof ApiTimeRoute
  '/': typeof AuthedIndexRoute
  '/event/$eventId': typeof AuthedEventEventIdRoute
  '/api/cron/cycle': typeof ApiCronCycleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/admin': typeof AuthedAdminRoute
  '/_authed/edge-ai': typeof AuthedEdgeAiRoute
  '/_authed/performance': typeof AuthedPerformanceRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/value': typeof AuthedValueRoute
  '/api/time': typeof ApiTimeRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/event/$eventId': typeof AuthedEventEventIdRoute
  '/api/cron/cycle': typeof ApiCronCycleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/edge-ai'
    | '/performance'
    | '/settings'
    | '/value'
    | '/api/time'
    | '/event/$eventId'
    | '/api/cron/cycle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin'
    | '/edge-ai'
    | '/performance'
    | '/settings'
    | '/value'
    | '/api/time'
    | '/'
    | '/event/$eventId'
    | '/api/cron/cycle'
  id:
    | '__root__'
    | '/_authed'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_authed/admin'
    | '/_authed/edge-ai'
    | '/_authed/performance'
    | '/_authed/settings'
    | '/_authed/value'
    | '/api/time'
    | '/_authed/'
    | '/_authed/event/$eventId'
    | '/api/cron/cycle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiTimeRoute: typeof ApiTimeRoute
  ApiCronCycleRoute: typeof ApiCronCycleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/edge-ai': {
      id: '/_authed/edge-ai'
      path: '/edge-ai'
      fullPath: '/edge-ai'
      preLoaderRoute: typeof AuthedEdgeAiRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/performance': {
      id: '/_authed/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthedPerformanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/value': {
      id: '/_authed/value'
      path: '/value'
      fullPath: '/value'
      preLoaderRoute: typeof AuthedValueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/time': {
      id: '/api/time'
      path: '/api/time'
      fullPath: '/api/time'
      preLoaderRoute: typeof ApiTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/event/$eventId': {
      id: '/_authed/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof AuthedEventEventIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/cron/cycle': {
      id: '/api/cron/cycle'
      path: '/api/cron/cycle'
      fullPath: '/api/cron/cycle'
      preLoaderRoute: typeof ApiCronCycleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRoute
  AuthedEdgeAiRoute: typeof AuthedEdgeAiRoute
  AuthedPerformanceRoute: typeof AuthedPerformanceRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedValueRoute: typeof AuthedValueRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedEventEventIdRoute: typeof AuthedEventEventIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRoute,
  AuthedEdgeAiRoute: AuthedEdgeAiRoute,
  AuthedPerformanceRoute: AuthedPerformanceRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedValueRoute: AuthedValueRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedEventEventIdRoute: AuthedEventEventIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiTimeRoute: ApiTimeRoute,
  ApiCronCycleRoute: ApiCronCycleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
