window.RUTA_DATA = {
  "meta": {
    "name": "RutaFútbol PY",
    "version": "0.2.0",
    "generatedAt": "2026-07-22",
    "language": "es-PY",
    "sourceNote": "Partidos: APF. Coordenadas y navegación: Google Maps.",
    "sourceUrl": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026"
  },
  "matches": [
    {
      "id": "MATCH-2026-CL-F01-01",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 1,
      "date": "2026-07-24",
      "time": "16:00",
      "timezone": "America/Asuncion",
      "home": "Sportivo 2 de Mayo",
      "away": "Club Rubio Ñu",
      "stadiumId": "rio-parapiti",
      "stadium": "Estadio Río Parapití",
      "city": "Pedro Juan Caballero",
      "department": "Amambay",
      "lat": -22.5368,
      "lng": -55.7407,
      "maps": "https://www.google.com/maps?q=-22.5368,-55.7407",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F01-02",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 1,
      "date": "2026-07-24",
      "time": "18:30",
      "timezone": "America/Asuncion",
      "home": "Cerro Porteño",
      "away": "Sportivo Trinidense",
      "stadiumId": "nueva-olla",
      "stadium": "Ueno La Nueva Olla",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.2999,
      "lng": -57.63752,
      "maps": "https://www.google.com/maps?q=-25.2999,-57.63752",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F01-03",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 1,
      "date": "2026-07-25",
      "time": "16:00",
      "timezone": "America/Asuncion",
      "home": "Recoleta FC",
      "away": "Sportivo San Lorenzo",
      "stadiumId": "ricardo-gregor",
      "stadium": "Estadio Ricardo Gregor",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.27577,
      "lng": -57.55175,
      "maps": "https://www.google.com/maps?q=-25.27577,-57.55175",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F01-04",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 1,
      "date": "2026-07-25",
      "time": "18:30",
      "timezone": "America/Asuncion",
      "home": "Sportivo Ameliano",
      "away": "Club Nacional",
      "stadiumId": "pikysyry",
      "stadium": "Estadio La Fortaleza del Pikysyry",
      "city": "Villeta",
      "department": "Central",
      "lat": -25.4973875,
      "lng": -57.496234375,
      "maps": "https://www.google.com/maps?q=-25.4973875,-57.496234375",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F01-05",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 1,
      "date": "2026-07-26",
      "time": "16:00",
      "timezone": "America/Asuncion",
      "home": "Club Olimpia",
      "away": "Club Libertad",
      "stadiumId": "defensores-chaco",
      "stadium": "Ueno Defensores del Chaco",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.292072,
      "lng": -57.657381,
      "maps": "https://www.google.com/maps?q=-25.292072,-57.657381",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F01-06",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 1,
      "date": "2026-07-26",
      "time": "18:30",
      "timezone": "America/Asuncion",
      "home": "Club Guaraní",
      "away": "Sportivo Luqueño",
      "stadiumId": "erico-galeano",
      "stadium": "Estadio Lic. Erico Galeano Segovia",
      "city": "Capiatá",
      "department": "Central",
      "lat": -25.36064,
      "lng": -57.43749,
      "maps": "https://www.google.com/maps?q=-25.36064,-57.43749",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F02-01",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 2,
      "date": "2026-07-28",
      "time": "16:00",
      "timezone": "America/Asuncion",
      "home": "Club Rubio Ñu",
      "away": "Sportivo Ameliano",
      "stadiumId": "la-arboleda",
      "stadium": "La Arboleda",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.25755,
      "lng": -57.5751,
      "maps": "https://www.google.com/maps?q=-25.25755,-57.5751",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F02-02",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 2,
      "date": "2026-07-28",
      "time": "18:30",
      "timezone": "America/Asuncion",
      "home": "Sportivo 2 de Mayo",
      "away": "Cerro Porteño",
      "stadiumId": "rio-parapiti",
      "stadium": "Estadio Río Parapití",
      "city": "Pedro Juan Caballero",
      "department": "Amambay",
      "lat": -22.5368,
      "lng": -55.7407,
      "maps": "https://www.google.com/maps?q=-22.5368,-55.7407",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F02-03",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 2,
      "date": "2026-07-29",
      "time": "16:00",
      "timezone": "America/Asuncion",
      "home": "Sportivo Luqueño",
      "away": "Sportivo Trinidense",
      "stadiumId": "luis-salinas",
      "stadium": "Estadio Luis Salinas Tanasio",
      "city": "Itauguá",
      "department": "Central",
      "lat": -25.395917,
      "lng": -57.340694,
      "maps": "https://www.google.com/maps?q=-25.395917,-57.340694",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F02-04",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 2,
      "date": "2026-07-29",
      "time": "18:30",
      "timezone": "America/Asuncion",
      "home": "Club Nacional",
      "away": "Club Olimpia",
      "stadiumId": "arsenio-erico",
      "stadium": "Estadio Arsenio Erico",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.29831,
      "lng": -57.64002,
      "maps": "https://www.google.com/maps?q=-25.29831,-57.64002",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F02-05",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 2,
      "date": "2026-07-30",
      "time": "16:00",
      "timezone": "America/Asuncion",
      "home": "Sportivo San Lorenzo",
      "away": "Club Guaraní",
      "stadiumId": "gunther-vogel",
      "stadium": "Estadio Gunther Vogel",
      "city": "San Lorenzo",
      "department": "Central",
      "lat": -25.34,
      "lng": -57.5,
      "maps": "https://www.google.com/maps?q=-25.34,-57.5",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F02-06",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 2,
      "date": "2026-07-30",
      "time": "18:30",
      "timezone": "America/Asuncion",
      "home": "Club Libertad",
      "away": "Recoleta FC",
      "stadiumId": "la-huerta",
      "stadium": "Ueno La Huerta",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.27776,
      "lng": -57.61105,
      "maps": "https://www.google.com/maps?q=-25.27776,-57.61105",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F03-01",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 3,
      "date": "2026-08-01",
      "time": "16:00",
      "timezone": "America/Asuncion",
      "home": "Sportivo Ameliano",
      "away": "Sportivo 2 de Mayo",
      "stadiumId": "pikysyry",
      "stadium": "Estadio La Fortaleza del Pikysyry",
      "city": "Villeta",
      "department": "Central",
      "lat": -25.4973875,
      "lng": -57.496234375,
      "maps": "https://www.google.com/maps?q=-25.4973875,-57.496234375",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F03-02",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 3,
      "date": "2026-08-01",
      "time": "18:30",
      "timezone": "America/Asuncion",
      "home": "Cerro Porteño",
      "away": "Sportivo Luqueño",
      "stadiumId": "nueva-olla",
      "stadium": "Ueno La Nueva Olla",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.2999,
      "lng": -57.63752,
      "maps": "https://www.google.com/maps?q=-25.2999,-57.63752",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F03-03",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 3,
      "date": "2026-08-02",
      "time": "16:00",
      "timezone": "America/Asuncion",
      "home": "Club Olimpia",
      "away": "Club Rubio Ñu",
      "stadiumId": "defensores-chaco",
      "stadium": "Ueno Defensores del Chaco",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.292072,
      "lng": -57.657381,
      "maps": "https://www.google.com/maps?q=-25.292072,-57.657381",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F03-04",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 3,
      "date": "2026-08-02",
      "time": "18:30",
      "timezone": "America/Asuncion",
      "home": "Club Guaraní",
      "away": "Club Libertad",
      "stadiumId": "la-arboleda",
      "stadium": "La Arboleda",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.25755,
      "lng": -57.5751,
      "maps": "https://www.google.com/maps?q=-25.25755,-57.5751",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F03-05",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 3,
      "date": "2026-08-03",
      "time": "16:00",
      "timezone": "America/Asuncion",
      "home": "Sportivo Trinidense",
      "away": "Sportivo San Lorenzo",
      "stadiumId": "martin-torres",
      "stadium": "Estadio Martín Torres",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.259722,
      "lng": -57.583889,
      "maps": "https://www.google.com/maps?q=-25.259722,-57.583889",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    },
    {
      "id": "MATCH-2026-CL-F03-06",
      "season": "2026",
      "competition": "Torneo Clausura – Copa de Primera",
      "round": 3,
      "date": "2026-08-03",
      "time": "18:30",
      "timezone": "America/Asuncion",
      "home": "Recoleta FC",
      "away": "Club Nacional",
      "stadiumId": "ricardo-gregor",
      "stadium": "Estadio Ricardo Gregor",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.27577,
      "lng": -57.55175,
      "maps": "https://www.google.com/maps?q=-25.27577,-57.55175",
      "status": "Programado",
      "apfProgram": "https://www.apf.org.py/noticias/asi-iniciara-el-torneo-clausura-2026",
      "checkedAt": "2026-07-22",
      "quality": "Alta"
    }
  ],
  "stadiums": [
    {
      "id": "rio-parapiti",
      "name": "Estadio Río Parapití",
      "alias": "",
      "city": "Pedro Juan Caballero",
      "department": "Amambay",
      "lat": -22.5368,
      "lng": -55.7407,
      "regularClubs": [
        "Sportivo 2 de Mayo"
      ],
      "temporaryClubs": [],
      "venueType": "regular",
      "maps": "https://www.google.com/maps?q=-22.5368,-55.7407",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "nueva-olla",
      "name": "Ueno La Nueva Olla",
      "alias": "General Pablo Rojas",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.2999,
      "lng": -57.63752,
      "regularClubs": [
        "Cerro Porteño"
      ],
      "temporaryClubs": [],
      "venueType": "regular",
      "maps": "https://www.google.com/maps?q=-25.2999,-57.63752",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "ricardo-gregor",
      "name": "Estadio Ricardo Gregor",
      "alias": "",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.27577,
      "lng": -57.55175,
      "regularClubs": [
        "Recoleta FC"
      ],
      "temporaryClubs": [],
      "venueType": "regular",
      "maps": "https://www.google.com/maps?q=-25.27577,-57.55175",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "pikysyry",
      "name": "Estadio La Fortaleza del Pikysyry",
      "alias": "Ameliano – Villeta",
      "city": "Villeta",
      "department": "Central",
      "lat": -25.4973875,
      "lng": -57.496234375,
      "regularClubs": [
        "Sportivo Ameliano"
      ],
      "temporaryClubs": [],
      "venueType": "regular",
      "maps": "https://www.google.com/maps?q=-25.4973875,-57.496234375",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "defensores-chaco",
      "name": "Ueno Defensores del Chaco",
      "alias": "",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.292072,
      "lng": -57.657381,
      "regularClubs": [],
      "temporaryClubs": [
        "Club Olimpia"
      ],
      "venueType": "neutral/temporary",
      "maps": "https://www.google.com/maps?q=-25.292072,-57.657381",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "erico-galeano",
      "name": "Estadio Lic. Erico Galeano Segovia",
      "alias": "Estadio Deportivo Capiatá",
      "city": "Capiatá",
      "department": "Central",
      "lat": -25.36064,
      "lng": -57.43749,
      "regularClubs": [
        "Deportivo Capiatá"
      ],
      "temporaryClubs": [
        "Club Guaraní"
      ],
      "venueType": "regular/temporary",
      "maps": "https://www.google.com/maps?q=-25.36064,-57.43749",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "la-arboleda",
      "name": "La Arboleda",
      "alias": "",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.25755,
      "lng": -57.5751,
      "regularClubs": [
        "Club Rubio Ñu"
      ],
      "temporaryClubs": [
        "Club Guaraní"
      ],
      "venueType": "regular/temporary",
      "maps": "https://www.google.com/maps?q=-25.25755,-57.5751",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "luis-salinas",
      "name": "Estadio Luis Salinas Tanasio",
      "alias": "Antes Juan Canuto Pettengill",
      "city": "Itauguá",
      "department": "Central",
      "lat": -25.395917,
      "lng": -57.340694,
      "regularClubs": [
        "Sportivo Luqueño",
        "12 de Octubre de Itauguá"
      ],
      "temporaryClubs": [],
      "venueType": "regular",
      "maps": "https://www.google.com/maps?q=-25.395917,-57.340694",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "arsenio-erico",
      "name": "Estadio Arsenio Erico",
      "alias": "La Visera",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.29831,
      "lng": -57.64002,
      "regularClubs": [
        "Club Nacional"
      ],
      "temporaryClubs": [],
      "venueType": "regular",
      "maps": "https://www.google.com/maps?q=-25.29831,-57.64002",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "gunther-vogel",
      "name": "Estadio Gunther Vogel",
      "alias": "Antes Ciudad Universitaria",
      "city": "San Lorenzo",
      "department": "Central",
      "lat": -25.34,
      "lng": -57.5,
      "regularClubs": [
        "Sportivo San Lorenzo"
      ],
      "temporaryClubs": [],
      "venueType": "regular",
      "maps": "https://www.google.com/maps?q=-25.34,-57.5",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "la-huerta",
      "name": "Ueno La Huerta",
      "alias": "La Huerta",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.27776,
      "lng": -57.61105,
      "regularClubs": [
        "Club Libertad"
      ],
      "temporaryClubs": [],
      "venueType": "regular",
      "maps": "https://www.google.com/maps?q=-25.27776,-57.61105",
      "verifiedAt": "2026-07-22"
    },
    {
      "id": "martin-torres",
      "name": "Estadio Martín Torres",
      "alias": "La Bombonera",
      "city": "Asunción",
      "department": "Capital",
      "lat": -25.259722,
      "lng": -57.583889,
      "regularClubs": [
        "Sportivo Trinidense"
      ],
      "temporaryClubs": [],
      "venueType": "regular",
      "maps": "https://www.google.com/maps?q=-25.259722,-57.583889",
      "verifiedAt": "2026-07-22"
    }
  ],
  "clubs": [
    "Cerro Porteño",
    "Club Guaraní",
    "Club Libertad",
    "Club Nacional",
    "Club Olimpia",
    "Club Rubio Ñu",
    "Recoleta FC",
    "Sportivo 2 de Mayo",
    "Sportivo Ameliano",
    "Sportivo Luqueño",
    "Sportivo San Lorenzo",
    "Sportivo Trinidense"
  ]
};
