import type { Brand } from "../../shared/ids/brand";
import { unsafeBrand } from "../../shared/ids/brand";
import { err, ok, type Result } from "../../shared/result/result";
import { primitiveError, type PrimitiveError } from "../primitives/errors";

/**
 * Every domain identifier is a branded string. Two families exist:
 *
 *  - *Authored* identifiers (`ProcedureId`, `RuleId`, `DocumentTypeId`, ...)
 *    are stable, human-readable slugs owned by the knowledge base. They are
 *    authored, reviewed and referenced by rules, so they must be readable and
 *    stable - never random.
 *  - *Record* identifiers (`UserCaseId`, `CaseEvaluationId`, ...) identify rows
 *    and are UUIDs generated by the database.
 *
 * Derived keys (`RequiredProcedureKey`, `RequiredDocumentKey`) are neither:
 * they are deterministic functions of semantic content and are generated by
 * `case-engine/canonicalization`. They must never be random UUIDs.
 */
const SLUG_PATTERN = /^[a-z0-9]+(?:[-.][a-z0-9]+)*$/u;
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/u;

function makeSlugId<Tag extends string>(
  tag: Tag,
  value: string,
  maxLength = 96,
): Result<Brand<string, Tag>, PrimitiveError> {
  if (value.length === 0 || value.length > maxLength) {
    return err(primitiveError(tag, `length must be 1..${maxLength}, received ${value.length}`));
  }
  if (!SLUG_PATTERN.test(value)) {
    return err(
      primitiveError(tag, `expected lower-case dotted/dashed slug, received "${value}"`),
    );
  }
  return ok(unsafeBrand<string, Tag>(value));
}

function makeUuidId<Tag extends string>(tag: Tag, value: string): Result<Brand<string, Tag>, PrimitiveError> {
  if (!UUID_PATTERN.test(value)) {
    return err(primitiveError(tag, `expected a UUID, received "${value}"`));
  }
  return ok(unsafeBrand<string, Tag>(value));
}

/* -------------------------------------------------------------------------- */
/* Knowledge base - authored identities                                        */
/* -------------------------------------------------------------------------- */

export type RuleId = Brand<string, "RuleId">;
export type RuleSetId = Brand<string, "RuleSetId">;
export type SourceId = Brand<string, "SourceId">;
export type ProcedureId = Brand<string, "ProcedureId">;
export type DocumentTypeId = Brand<string, "DocumentTypeId">;
export type AuthorityId = Brand<string, "AuthorityId">;
export type OfficeId = Brand<string, "OfficeId">;
export type PathwayId = Brand<string, "PathwayId">;
export type PathwayDefinitionId = Brand<string, "PathwayDefinitionId">;
export type ProductPolicyId = Brand<string, "ProductPolicyId">;
export type ProductCoverageId = Brand<string, "ProductCoverageId">;
export type FeeIndexId = Brand<string, "FeeIndexId">;
export type ExternalCostCode = Brand<string, "ExternalCostCode">;
export type FeeComponentCode = Brand<string, "FeeComponentCode">;
export type FormalityCode = Brand<string, "FormalityCode">;
export type VisaPurposeCode = Brand<string, "VisaPurposeCode">;

export const makeRuleId = (v: string) => makeSlugId("RuleId", v);
export const makeRuleSetId = (v: string) => makeSlugId("RuleSetId", v);
export const makeSourceId = (v: string) => makeSlugId("SourceId", v);
export const makeProcedureId = (v: string) => makeSlugId("ProcedureId", v);
export const makeDocumentTypeId = (v: string) => makeSlugId("DocumentTypeId", v);
export const makeAuthorityId = (v: string) => makeSlugId("AuthorityId", v);
export const makeOfficeId = (v: string) => makeSlugId("OfficeId", v);
export const makePathwayId = (v: string) => makeSlugId("PathwayId", v);
export const makePathwayDefinitionId = (v: string) => makeSlugId("PathwayDefinitionId", v);
export const makeProductPolicyId = (v: string) => makeSlugId("ProductPolicyId", v);
export const makeProductCoverageId = (v: string) => makeSlugId("ProductCoverageId", v);
export const makeFeeIndexId = (v: string) => makeSlugId("FeeIndexId", v);
export const makeExternalCostCode = (v: string) => makeSlugId("ExternalCostCode", v);
export const makeFeeComponentCode = (v: string) => makeSlugId("FeeComponentCode", v);
export const makeFormalityCode = (v: string) => makeSlugId("FormalityCode", v);
export const makeVisaPurposeCode = (v: string) => makeSlugId("VisaPurposeCode", v);

/* -------------------------------------------------------------------------- */
/* Knowledge base - revision identities                                        */
/* -------------------------------------------------------------------------- */

export type RuleRevisionId = Brand<string, "RuleRevisionId">;
export type RuleSetRevisionId = Brand<string, "RuleSetRevisionId">;
export type SourceRevisionId = Brand<string, "SourceRevisionId">;
export type OfficeRevisionId = Brand<string, "OfficeRevisionId">;
export type PathwayDefinitionRevisionId = Brand<string, "PathwayDefinitionRevisionId">;
export type ProductPolicyRevisionId = Brand<string, "ProductPolicyRevisionId">;
export type ProductCoverageRevisionId = Brand<string, "ProductCoverageRevisionId">;
export type FeeIndexRevisionId = Brand<string, "FeeIndexRevisionId">;

export const makeRuleRevisionId = (v: string) => makeUuidId("RuleRevisionId", v);
export const makeRuleSetRevisionId = (v: string) => makeUuidId("RuleSetRevisionId", v);
export const makeSourceRevisionId = (v: string) => makeUuidId("SourceRevisionId", v);
export const makeOfficeRevisionId = (v: string) => makeUuidId("OfficeRevisionId", v);
export const makePathwayDefinitionRevisionId = (v: string) =>
  makeUuidId("PathwayDefinitionRevisionId", v);
export const makeProductPolicyRevisionId = (v: string) => makeUuidId("ProductPolicyRevisionId", v);
export const makeProductCoverageRevisionId = (v: string) =>
  makeUuidId("ProductCoverageRevisionId", v);
export const makeFeeIndexRevisionId = (v: string) => makeUuidId("FeeIndexRevisionId", v);

/* -------------------------------------------------------------------------- */
/* Records                                                                     */
/* -------------------------------------------------------------------------- */

export type UserCaseId = Brand<string, "UserCaseId">;
export type CaseEvaluationId = Brand<string, "CaseEvaluationId">;
export type DocumentInstanceId = Brand<string, "DocumentInstanceId">;
export type EvaluationBundleId = Brand<string, "EvaluationBundleId">;
export type UserId = Brand<string, "UserId">;

export const makeUserCaseId = (v: string) => makeUuidId("UserCaseId", v);
export const makeCaseEvaluationId = (v: string) => makeUuidId("CaseEvaluationId", v);
export const makeDocumentInstanceId = (v: string) => makeUuidId("DocumentInstanceId", v);
export const makeEvaluationBundleId = (v: string) => makeUuidId("EvaluationBundleId", v);
export const makeUserId = (v: string) => makeUuidId("UserId", v);

/* -------------------------------------------------------------------------- */
/* Derived keys                                                                */
/* -------------------------------------------------------------------------- */

/**
 * Deterministic identity of a required procedure within one evaluation.
 * Format v1: `rp1:<procedureId>|<canonical parameters>[|<discriminator>]`.
 */
export type RequiredProcedureKey = Brand<string, "RequiredProcedureKey">;

/**
 * Deterministic identity of a required document within one evaluation.
 * Format v1: `rd1:<requiredProcedureKey>|<documentTypeId>|<issuingCountry>|<discriminator>`.
 */
export type RequiredDocumentKey = Brand<string, "RequiredDocumentKey">;

/**
 * Only the canonicalization module in `case-engine` may mint derived keys, and
 * only from canonical semantic content.
 */
export function unsafeRequiredProcedureKey(value: string): RequiredProcedureKey {
  return unsafeBrand<string, "RequiredProcedureKey">(value);
}

export function unsafeRequiredDocumentKey(value: string): RequiredDocumentKey {
  return unsafeBrand<string, "RequiredDocumentKey">(value);
}

/* -------------------------------------------------------------------------- */
/* Test / fixture constructors                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Compile-time constants used by fixtures and seeds. The value is *not*
 * validated; `tests/unit` asserts that every constant used in shipped code
 * would also pass the corresponding `makeX` validator.
 */
export function identifierConstant<Tag extends string>(value: string): Brand<string, Tag> {
  return unsafeBrand<string, Tag>(value);
}

export { SLUG_PATTERN, UUID_PATTERN };
